# Generated by Django 5.0.4 on 2024-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertodo',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='todo',
            field=models.TextField(null=True, verbose_name='Todo'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
